version: "2"

services:
  web:
    build: .
    ports:
      - "80:5000"
    links:
      - redis
    networks:
      - compose-demo-bridge

  redis:
    image: redis
    ports: ["6379"]
    networks:
      - compose-demo-bridge


networks:
  compose-demo-bridge:
